### ISSUE TITLE
Aggregating function outputs into a `dict`?

### ISSUE THREAD

**Issue by egorchakov** [pipefunc/pipefunc#456]
Hi @basnijholt, thanks for your work on `pipefunc`! 

We've recently started using it in [`rbyte`](https://github.com/yaak-ai/rbyte). Our use case essentially boils down to executing DAGs of functions taking/returning [`polars.DataFrame`](https://docs.pola.rs/api/python/stable/reference/dataframe/index.html)'s or `PyTree`s thereof as part of dataset preprocessing.

One snag I stumbled upon is aggregating a bunch of function outputs into a `dict`. As a first pass I'm resorting to something like [this](https://github.com/yaak-ai/rbyte/blob/main/src/rbyte/utils/_pipefunc.py#L7), [used](https://github.com/yaak-ai/rbyte/blob/main/config/_templates/dataset/yaak.yaml#L62) with [`hydra`](https://hydra.cc/):

```yaml
_target_: pipefunc.PipeFunc
func:
  _target_: hydra.utils.get_method
  path: rbyte.utils.make_dict
bound:
  k0: meta
  k1: mcap
renames:
  v0: meta.data
  v1: mcap.data
output_name: data
```

Is/could there be a better/cleaner way of achieving this with `pipefunc`? Perhaps via some kind of `*args`/`**kwargs` support?
